# Grafana
grafana:
  adminPassword: "change-me"          # set new secret
  ingress:
    enabled: true
    ingressClassName: alb              
    annotations:
      alb.ingress.kubernetes.io/scheme: internal  
      alb.ingress.kubernetes.io/target-type: ip   
    hosts:
      - grafana.internal.example.com   # replace with internal DNS name

# Prometheus
prometheus:
  prometheusSpec:
    retention: 15d                     
    storageSpec:                       
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi            

# Alertmanager
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi