apiVersion: batch/v1
kind: Job
metadata:
  name: forecast-train
  namespace: mlops
spec:
  ttlSecondsAfterFinished: 3600  
  backoffLimit: 0                 
  template:
    spec:
      serviceAccountName: train-sa
      restartPolicy: Never
      containers:
      - name: trainer
        image: 765568065512.dkr.ecr.us-east-1.amazonaws.com/ai-playground-app:train-v1
        env:

          - name: MLFLOW_TRACKING_URI
            value: "http://mlflow-service.mlops.svc.cluster.local:5000"

          - name: EXPERIMENT_NAME
            value: "forecast-demo"
          - name: MODEL_NAME
            value: "ForecastModel"


          - name: S3_DATA_URI
            value: "s3://ai-playground-mlflow-7ef1a5fd/data/example_retail_sales.csv"

        command: ["/bin/sh","-c"]
        args:
          - |
            set -e
            echo "Starting training…"
            python train.py --csv "$S3_DATA_URI"
            echo "Training completed."