# k8s/localmlflow/mlflow-proxy-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-proxy-config
  namespace: mlops
data:
  nginx.conf: |
    events {}
    http {
      upstream mlflow_upstream {
        server mlflow-service.mlops.svc.cluster.local:5000;
      }

      server {
        listen 5000;

        location / {
          proxy_set_header Host localhost;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://mlflow_upstream;
        }
      }
    }