apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
  namespace: mlops
data:
  artifact_root: "/mlflow/mlruns"
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-config
  namespace: mlops
type: Opaque
stringData:
  backend_store_uri: "sqlite:////mlflow/db/mlflow.db"