apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      volumes:
        - name: mlruns-storage
          persistentVolumeClaim:
            claimName: mlruns-pvc
        - name: mlflow-db-storage
          persistentVolumeClaim:
            claimName: mlflow-db-pvc
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlruns-storage
              mountPath: /mlflow/mlruns
            - name: mlflow-db-storage
              mountPath: /mlflow/db
          env:
            - name: BACKEND_STORE_URI
              valueFrom:
                secretKeyRef:
                  name: mlflow-config
                  key: backend_store_uri
            - name: ARTIFACT_ROOT
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: artifact_root
            - name: MLFLOW_SERVER_ALLOWED_HOSTS
              value: "mlflow-service.mlops.svc.cluster.local,mlflow-service,localhost,127.0.0.1"
          command: ["mlflow"]
          args: ["server", "--host", "0.0.0.0", "--port", "5000",
                 "--backend-store-uri", "$(BACKEND_STORE_URI)",
                 "--default-artifact-root", "$(ARTIFACT_ROOT)",
                 "--allowed-hosts", "mlflow-service.mlops.svc.cluster.local,mlflow-service,localhost,127.0.0.1"]

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: mlops
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP