apiVersion: batch/v1
kind: Job
metadata:
  name: forecast-train
  namespace: mlops
spec:
  ttlSecondsAfterFinished: 3600   # auto-delete 1 hour after completion
  backoffLimit: 0                 
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: mlruns-storage
          persistentVolumeClaim:
            claimName: mlruns-pvc
        - name: mlflow-db-storage
          persistentVolumeClaim:
            claimName: mlflow-db-pvc
      containers:
        - name: trainer
          image: train:dev
          imagePullPolicy: IfNotPresent
          env:
          
            - name: PYTHONUNBUFFERED
              value: "1"

            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow-proxy.mlops.svc.cluster.local:5000"

            - name: EXPERIMENT_NAME
              value: "forecast-demo"
            - name: MODEL_NAME
              value: "ForecastModel"

            - name: S3_DATA_URI
              value: "s3://ai-playground-mlflow-da8b551a/data/latest.csv"

          volumeMounts:
            - name: mlruns-storage
              mountPath: /mlflow/mlruns
            - name: mlflow-db-storage
              mountPath: /mlflow/db

          command: ["/bin/sh","-c"]
          args:
            - |
              set -e
              echo "Starting training…"
              python train.py --csv example_retail_sales.csv
              echo "Training completed."