apiVersion: v1
kind: Pod
metadata:
  name: rds-access-test
  namespace: mlops
spec:
  serviceAccountName: mlflow-sa
  restartPolicy: Never
  containers:
  - name: postgres-client
    image: public.ecr.aws/docker/library/postgres:16
    env:
      - name: PGHOST
        value: "terraform-20251003201513804100000001.c8d2oaa62muf.us-east-1.rds.amazonaws.com"
      - name: PGPORT
        value: "5432"
      - name: PGUSER
        value: "mlflow"               
      - name: PGPASSWORD
        value: "S3curePassw0rd!"   
      - name: PGDATABASE
        value: "mlflow"               
    command: ["sh", "-c"]
    args:
      - |
        echo "Testing RDS connection..."
        psql "sslmode=require" -c "SELECT version();"