apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image:  765568065512.dkr.ecr.us-east-1.amazonaws.com/ai-playground-app:ai-app-v1
        env:
        - name: MLFLOW_TRACKING_URI
          value: http://mlflow-service:5000
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
spec:
  type: ClusterIP                    
  selector:
    app: app                          
  ports:
  - port: 80
    targetPort: 80
