apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
        - name: mlruns-storage
          persistentVolumeClaim:
            claimName: mlruns-pvc
        - name: mlflow-db-storage
          persistentVolumeClaim:
            claimName: mlflow-db-pvc
      containers:
        - name: app
          image: app:dev
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: mlflow-client-config
          ports:
          - name: http
            containerPort: 8000
          volumeMounts:
            - name: mlruns-storage
              mountPath: /mlflow/mlruns
            - name: mlflow-db-storage
              mountPath: /mlflow/db
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
  labels:
    app: app
spec:
  type: ClusterIP                    
  selector:
    app: app                          
  ports:
  - name: http
    port: 8000
    targetPort: 8000
