apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlruns-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
  volumeName: shared-mlflow-pv-app

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-db-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeName: shared-mlflow-db-pv-app