apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-mlflow-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/mlflow/artifacts
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-mlflow-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/mlflow/db