apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: 765568065512.dkr.ecr.us-east-1.amazonaws.com/ai-playground-app:latest
        envFrom:
        - configMapRef:
            name: mlflow-client-config
        ports:
        - name: http
          containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
  labels:
    app: app
spec:
  type: ClusterIP                    
  selector:
    app: app                          
  ports:
  - name: http
    port: 8000
    targetPort: 8000
