
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-ingress
  namespace: mlops
  annotations:
    alb.ingress.kubernetes.io/scheme: internal        
    alb.ingress.kubernetes.io/target-type: ip         
spec:
  ingressClassName: alb                               
  rules:
  - host: mlflow.internal.example.com                 # replace with internal DNS name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mlflow-service                      
            port:
              number: 5000